import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dashboard from "@/components/dashboard/dashboard";
import Mainbody from "@/components/mainbody/mainbody";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} main`}>
        <Dashboard />
        {children}
        <Mainbody />
      </body>
    </html>
  );
}
